project/website/config/routes.rb
Rails.application.routes.draw do

  resources :items

  get 'invoices/new' => 'invoice#new'

  get 'settings/admin'

  get 'settings/account'

  get 'settings/referrals'

  get 'client/index'

  get 'client/new'

  get 'clients' => 'client#index'

  get 'clients/new' => 'client#new'

  get 'invoices' => 'invoice#index'

  get 'home/index'

  root 'items#index'

end

project/website/app/models/item.rb
class Item

  def initialize(name='', description='', price='', track_inventory=false, inventory='')
    @name = name
    @description = description
    @price = price
    @track_inventory = track_inventory
    @inventory = inventory
  end

  def name
    @name
  end

  def description
    @description
  end

  def price
    @price
  end

  def track_inventory
    @track_inventory
  end

  def inventory
    @inventory
  end


end

project/website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project/website/app/controllers/client_controller.rb
class ClientController < ApplicationController
  def index
  end

  def new
  end
end

project/website/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

project/website/app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController
  def new
  end
end

project/website/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    json= ' {
        "name": "tshirt",
        "description": "Una camisa de playa",
        "price": "23.34",
        "track_inventory": true,
        "inventory": 23
    }'

    json2= ' {
        "name": "Pantalon",
        "description": "Larga descripción",
        "price": "23.34",
        "track_inventory": true,
        "inventory": 23
    }'
    item_hash = JSON.parse json
    item= Item.new(item_hash['name'], item_hash['description'], item_hash['price'], item_hash['track_inventory'], item_hash['inventory'])

    item_hash = JSON.parse json2
    item2= Item.new(item_hash['name'], item_hash['description'], item_hash['price'], item_hash['track_inventory'], item_hash['inventory'])



    @items = Array.new #=> []
    @items.push(item)
    @items.push(item2)

  end

  def new
    @item= Item.new()
  end

  def edit
    json= ' {
        "name": "tshirt",
        "description": "Una camisa de playa",
        "price": "23.34",
        "track_inventory": true,
        "inventory": 23
    }'
    item_hash = JSON.parse json
    @item= Item.new(item_hash['name'], item_hash['description'], item_hash['price'], item_hash['track_inventory'], item_hash['inventory'])
  end

  def create
    flash[:alert] = 'No se puede crear. [Modo Solo Lectura]'
    #flash[:notice] = 'Item creado exitosamente'
    #flash[:error] = 'Item creado exitosamente'
    redirect_to :action => 'edit', :id => 3
  end

  def update
    flash[:alert] = 'No se puede actualizar. [Modo Solo Lectura]'
    #flash[:notice] = 'Item actualizado exitosamente'
    #flash[:error] = 'Item actualizado exitosamente'
    redirect_to :action => 'edit', :id => 3
  end

  def destroy
    flash[:alert] = 'No se puede eliminar. [Modo Solo Lectura]'
    #flash[:notice] = 'Item actualizado exitosamente'
    #flash[:error] = 'Item actualizado exitosamente'
    redirect_to :action => 'index'
  end

end

project/website/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def account
  end

  def referrals
  end
end

project/website/app/helpers/application_helper.rb
module ApplicationHelper
end

project/website/app/helpers/client_helper.rb
module ClientHelper
end

project/website/app/helpers/home_helper.rb
module HomeHelper
end

project/website/app/helpers/invoice_helper.rb
module InvoiceHelper
end

project/website/app/helpers/item_helper.rb
module ItemHelper
end

project/website/app/helpers/settings_helper.rb
module SettingsHelper
end

project/website/app/views/client/index.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Clientes
  </h1>
  <a href="/clients/new">
    <button type="button" class="btn btn-primary btn-lg" style="float: right; margin-top: 15px;">Crear Cliente</button>
  </a>
</header>


<table class="table">
  <thead>
  <tr class="active">
    <th>Organización</th>
    <th>Contacto</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>White Kitchen</td>
    <td>Cesar</td>
    <td>Cesar@whitekitchen.com</td>

    <td>234</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Web maintanence </td>
    <td>Montly support</td>

    <td>23</td>
  </tr>

  </tbody>
</table>

project/website/app/views/client/new.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Crear Cliente
  </h1>

</header>



  <form class="form-horizontal" role="form">

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <h4>
          <label class="control-label">Organización</label>
        </h4>
      </div>
    </div>


    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Nombre de Organización">
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <h4>
          <label class="control-label">Contactos</label>
        </h4>
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Nombre de Contacto">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Apellidos</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Apellidos de Contacto">
      </div>
    </div>


    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Email</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Email">
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <a href="#">Agregar otro contacto</a>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <h4>
          <label class="control-label">Detalles</label>
        </h4>
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Dirección</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Dirección">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Cuidad</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Cuidad">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">País</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="País">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Teléfono</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Teléfono">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Notas internas</label>

      <div class="col-sm-10">
        <textarea class="form-control" rows="3" placeholder="Notas internas"></textarea>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <a href="/items">
          <button type="button" class="btn btn-default">Cancelar</button>
        </a>
        <button type="submit" class="btn btn-success">Guardar</button>
      </div>
    </div>


  </form>

project/website/app/views/home/index.html.erb
<h1>
  Home
</h1>

project/website/app/views/invoice/index.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Facturas
  </h1>
  <a href="invoices/new">
  <button type="button" class="btn btn-primary btn-lg" style="float: right; margin-top: 15px;">Crear Factura</button>
    </a>
</header>


<table class="table">
  <thead>
  <tr class="active">
    <th>Factura</th>
    <th>Cliente</th>
    <th>Descripción</th>
    <th>Fecha</th>
    <th>Total</th>
    <th>Estado</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>1343</td>
    <td>John</td>
    <td>Casas</td>
    <td>10/23/14</td>
    <td>2000000</td>
    <td>Borrador</td>

  </tr>
  <tr>
    <td>3342</td>
    <td>Peter</td>
    <td>Material</td>
    <td>10/23/14</td>
    <td>2430000</td>
    <td>Completado</td>
  </tr>

  </tbody>
</table>

project/website/app/views/invoice/new.html.erb
  <header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
    <h1 style="float: left; margin-top: 16px;">
      Crear Factura
    </h1>

  </header>


  <form class="form-horizontal" role="form">
    <div class="form-group">
      <label for="inputEmail3" class=" col-sm-offset-5  col-sm-3 control-label">Cliente</label>

      <div class="col-sm-4">
        <input type="text" class="form-control" placeholder="Buscar Cliente">
      </div>
    </div>
    <div class="form-group">

      <div class="col-sm-5" >
        <input type="text" class="form-control" placeholder="Buscar Item">
      </div>



      <label for="inputEmail3" class="col-sm-3 control-label">Fecha</label>

      <div class="col-sm-4">
        <input type="text" class="form-control" placeholder="dd/mm/aaaa">
      </div>
    </div>
  </form>


  <table class="table " >
    <thead>
    <tr class="active">
      <th>Item</th>
      <th style="text-align: right;">Precio</th>
      <th style="text-align: right;">Cantidad</th>
      <th style="text-align: right;">Total de Línea</th>
      <th style="text-align: right;" width="5%;"></th>

    </tr>
    </thead>
    <tbody>
    <tr>
      <td>Camiseta</td>
      <td>
        <input type="text" class="form-control" placeholder="Cantidad" style="width: 90px; float: right; text-align: right;">
      </td>
      <td>
        <input type="text" class="form-control" placeholder="" style="width: 50px; float: right; text-align: right;">
      </td>
      <td style="text-align: right;">54</td>
      <td style="text-align: right;"><span class="glyphicon glyphicon-remove-sign titled" title="Eliminar" data-placement="left"  style=" color:#a9a9a9; font-size: 20px; margin-top: 5px;"></span></td>

    </tr>
    <tr>
      <td>Camiseta</td>
      <td>
        <input type="text" class="form-control" placeholder="Precio" style="width: 90px; float: right; text-align: right;">
      </td>
      <td>
        <input type="text" class="form-control" placeholder="" style="width: 50px;float: right;text-align: right;">
      </td>
      <td style="text-align: right;">54</td>
      <td style="text-align: right;"><span class="glyphicon glyphicon-remove-sign titled" title="Eliminar" data-placement="left" style=" color:#a9a9a9; font-size: 20px; margin-top: 5px;"></span></td>

    </tr>


    </tbody>
  </table>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-offset-8 col-sm4" style="text-align: right;">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <label for="inputEmail3" class="col-sm-6 control-label">Subtotal</label>
              <span for="inputEmail3" class="col-sm-6">343</span>
            </div>
            <div class="row">
              <label for="inputEmail3" class=" col-sm-6 control-label">Impuestos</label>
              <span for="inputEmail3" class="col-sm-6">343</span>
            </div>
            <div class="row">
              <label for="inputEmail3" class="col-sm-6 control-label">Total</label>
              <span for="inputEmail3" class="col-sm-6">343</span>
            </div>

            <div class="row">
              <label for="inputEmail3" class="col-sm-6" style="font-weight: normal;">Pago efectivo</label>
              <span for="inputEmail3" class="col-sm-6">$50</span>
            </div>
            <div class="row">
              <label for="inputEmail3" class="col-sm-6 control-label" style="font-weight: normal;">Pago tarjeta</label>
              <span for="inputEmail3" class="col-sm-6">$30</span>
            </div>

            <div class="row">
              <label for="inputEmail3" class="col-sm-6" style="font-weight: normal;"><a href="#" >Agregar pago</a></label>
            </div>

          </div>

          <div class="panel-footer">
            <div class="row">
              <label for="inputEmail3" class="col-sm-6 control-label">Balance</label>
              <span for="inputEmail3" class="col-sm-6">0</span>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>

project/website/app/views/items/_form.html.erb
<div class="form-group">
  <%= label_tag('item_name', 'Nombre', :class => 'col-sm-2 control-label') %>
  <div class="col-sm-10">
    <%= text_field(:item, :name, :class => 'form-control', :placeholder => 'Nombre', :autocomplete => 'off') %>
  </div>
</div>
<div class="form-group">
  <%= label_tag('item_description', 'Descripción', :class => 'col-sm-2 control-label') %>
  <div class="col-sm-10">
    <%= text_field(:item, :description, :class => 'form-control', :placeholder => 'Descripción', :autocomplete => 'off') %>
  </div>
</div>

<div class="form-group">
  <%= label_tag('item_price', 'Precio', :class => 'col-sm-2 control-label') %>

  <div class="col-sm-10">
    <%= text_field(:item, :price, :class => 'form-control', :placeholder => 'Price', :autocomplete => 'off') %>
  </div>
</div>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <div class="checkbox">
      <label>
        <%= check_box(:item, :track_inventory) %>
         Controlar inventario
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= label_tag('item_inventory', 'Inventario', :class => 'col-sm-2 control-label') %>

  <div class="col-sm-10">
    <%= text_field(:item, :inventory, :class => 'form-control', :placeholder => 'Price', :autocomplete => 'off') %>
  </div>
</div>

project/website/app/views/items/edit.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Editar Item
  </h1>
</header>
<%= render :partial => 'shared/alerts' %>
<%= form_tag('/items/2', :method => 'put', :class => 'form-horizontal', :role => 'form') do %>

    <%= render :partial => 'form', :item => @item, :locals => {:language => 'ingles'} %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <a href="/items">
          <button type="button" class="btn btn-default">Cancelar</button>
        </a>
        <button type="submit" class="btn btn-success">Guardar</button>
      </div>
    </div>
<% end %>

project/website/app/views/items/index.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Items
  </h1>
  <a href="/items/new">
    <button type="button" class="btn btn-primary btn-lg" style="float: right; margin-top: 15px;">Crear Item</button>
  </a>
</header>

<%= render :partial => 'shared/alerts' %>


<table class="table">
  <thead>
  <tr class="active">
    <th>Id</th>
    <th>Nombre de Item</th>
    <th>Descripción</th>
    <th>Inventario</th>
    <th>Precio</th>
    <th style="text-align: right;" width="10%;"></th>
  </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td>1</td>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td>---</td>
        <td>234</td>
        <td style="text-align: right;">
          <%= link_to edit_item_path(5) do %>
              <span class="glyphicon glyphicon-pencil titled" title="Editar"></span>
          <% end %>
          <%= link_to item_path(5), :method => :delete, :data => {:confirm => 'Are you sure?'} do %>
              <span class="glyphicon glyphicon-remove titled" title="Eliminar"></span>
          <% end %>
        </td>

      </tr>
  <% end %>

  </tbody>
</table>

project/website/app/views/items/new.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Crear Item
  </h1>
</header>

<%= render :partial => 'shared/alerts' %>

<%= form_tag('/items', :method => 'post', :class => 'form-horizontal', :role => 'form') do %>
    <%= render :partial => 'form', :item => @item, :locals => {:language => 'ingles'} %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <a href="/items">
          <button type="button" class="btn btn-default">Cancelar</button>
        </a>
        <button type="submit" class="btn btn-success">Guardar</button>
      </div>
    </div>
<% end %>

project/website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Factura Cohete</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <div class="sidebar">

    <div style="color: #428bca;text-align: center;">
      <a href="/">
        <span class="glyphicon glyphicon-leaf" style="font-size: 60px;  margin-top: 7px;"></span>
      </a>
    </div>
<a href="/invoices/new">
    <button type="button" class="btn btn-success btn-lg" style="width: 100%;margin-top: 30px;">Crear Factura</button>
</a>
    <div class="list-group" style="margin-top: 20px;">
      <a href="/invoices" class="list-group-item">Facturas</a>
      <a href="/items" class="list-group-item">Items</a>
      <a href="/clients" class="list-group-item">Clientes</a>
    </div>

    <div>
      <a href="/settings/account">
      <span class="icon glyphicon glyphicon-cog titled" title="Configuración"  style="margin-left: 30px;"></span>
      </a>
      <span class="icon glyphicon glyphicon-log-out titled" title="Cerrar Sesión" style="margin-left: 5px;"></span>


    </div>

  </div>
  <div class="content">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

project/website/app/views/settings/account.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Configuración
  </h1>

</header>

<ul class="nav nav-tabs" role="tablist" style="margin-bottom: 40px;">
  <li role="presentation" class="active"><a href="/settings/account">Mi Cuenta</a></li>
  <li role="presentation"><a href="/settings/admin">Admin</a></li>

</ul>



<div class="well well-sm">Cuenta de Usuario</div>



  <form class="form-horizontal" role="form" style="margin-left: 30px;">
    <div class="form-group">
      <span class="glyphicon glyphicon-envelope" style="margin-right: 5px; color:#a9a9a9;"></span><a href="#edit-email">luiscarlosch@gmail.com</a><span class="glyphicon glyphicon-pencil titled" title="Editar Email" data-placement="right"  style="margin-left: 5px; "></span>
    </div>
    <div class="form-group">

      <span class="glyphicon glyphicon-wrench" style="margin-right: 5px; color:#a9a9a9;"></span><a href="#edit-password">Cambiar Contraseña</a><span class="glyphicon glyphicon-pencil titled" title="Editar Contraseña" data-placement="right" style="margin-left: 5px; "></span>
    </div>
    <div class="form-group">

      <span class="glyphicon glyphicon-time" style="margin-right: 5px; color:#a9a9a9;"></span>Usuario desde: 12/2/2013
    </div>
    <div class="form-group">

      <span class="glyphicon glyphicon-remove-sign" style="margin-right: 5px; color:#a9a9a9;"></span><a href="#edit-password">Desactivar Cuenta</a>
    </div>



  </form>






<div class="well well-sm">Información de Contacto</div>



  <form class="form-horizontal" role="form">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Nombre">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Apellidos</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Descripción">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Teléfono</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Teléfono">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Organización</label>

      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Organización">
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <a href="/items">
          <button type="button" class="btn btn-default">Cancelar</button>
        </a>
        <button type="submit" class="btn btn-success">Guardar</button>
      </div>
    </div>
  </form>

project/website/app/views/settings/referrals.html.erb
<header style="height: 80px; border: 0px solid #000000; margin-bottom: 15px;">
  <h1 style="float: left; margin-top: 16px;">
    Configuración
  </h1>

</header>

<ul class="nav nav-tabs" role="tablist">
  <li role="presentation"><a href="/settings/account">Mi Cuenta</a></li>
  <li role="presentation" class="active"><a href="/settings/referrals">Programa de Referidos</a></li>
</ul>

project/website/app/views/shared/_alerts.html.erb
<% if flash[:success] -%>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= h flash[:success] %>
    </div>
<% end -%>

<% if flash[:notice] -%>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= h flash[:notice] %>
    </div>
<% end -%>

<% if flash[:alert] -%>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= h flash[:alert] %>
    </div>
<% end -%>

<% if flash[:error] -%>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= h flash[:error] %>
    </div>
<% end -%>